[[Wigxjpf]]
arch = "aarch64"
git-tree-sha1 = "0b616cdb7c5789792887a6149871d05362459701"
os = "macos"

    [[Wigxjpf.download]]
    sha256 = "47c66b48e4bbec529752046be4cac7aa281d745c57a9060f50ec41684a6d5f35"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.aarch64-apple-darwin.tar.gz"
[[Wigxjpf]]
arch = "aarch64"
git-tree-sha1 = "ca84c6e363a04dcb409cf4dc9906da45afe29233"
libc = "glibc"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "06ea23d5e4ae3725dc9970999091cd28dcdd98681a804ef630810f56d6c8ea7b"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.aarch64-linux-gnu.tar.gz"
[[Wigxjpf]]
arch = "aarch64"
git-tree-sha1 = "5506657b54d0df408cb258c754d9785c96eff929"
libc = "musl"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "df45c884694b073c3fc86b5d012e291ee84e4253de6603824c2d41d48a698700"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.aarch64-linux-musl.tar.gz"
[[Wigxjpf]]
arch = "aarch64"
git-tree-sha1 = "f65730160253648669aa4fec749b00efb39e889f"
os = "freebsd"

    [[Wigxjpf.download]]
    sha256 = "f8d169edc241aaccbbd1cef42a0580e27e780ea465a3d608b175a9c9e21dda64"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.aarch64-unknown-freebsd.tar.gz"
[[Wigxjpf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9402e0c687aa60e585e127bac8b48cec500149a9"
libc = "glibc"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "900adc628ea3c2da2cca9c2df81e2f0cc7b793672ac48a6dc3b540b6603da630"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.armv6l-linux-gnueabihf.tar.gz"
[[Wigxjpf]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "026390fc068a08e662be16451091e55cf158547a"
libc = "musl"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "49e23cfa7602bf1661a617d8838d78f665d240884c6cdc56d45b82eb2f5ae3d1"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.armv6l-linux-musleabihf.tar.gz"
[[Wigxjpf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "285e6e453a8f4b71ffc7bee211e2cb0b0144691b"
libc = "glibc"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "9b2113740f1736c788250a40094a69c4286f98ed3e96b0f2ec00a3bef9b65d4c"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.armv7l-linux-gnueabihf.tar.gz"
[[Wigxjpf]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a01161ec41694f77629da39813bd6e2194ae226c"
libc = "musl"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "0d5cbef99f632614876bdbd3277949157d11f61ca48ef1cfa05fb1716205f347"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.armv7l-linux-musleabihf.tar.gz"
[[Wigxjpf]]
arch = "i686"
git-tree-sha1 = "b4b2488d4298fc11ce021a380f95b3f67e401725"
libc = "glibc"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "2ccb7b2cee3b929ce24fb1a45d12c0767808af2b1e8a677bbcc78b3ef89c24e8"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.i686-linux-gnu.tar.gz"
[[Wigxjpf]]
arch = "i686"
git-tree-sha1 = "0a4cb4bda634351a2e7c118609bdce289254f8e8"
libc = "musl"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "a2fefac02b209438de08813e5cc8f5d7ecd27a87e4aabf657e8f8174ff6ebc5b"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.i686-linux-musl.tar.gz"
[[Wigxjpf]]
arch = "i686"
git-tree-sha1 = "d3e5c61ff72593432cee8a3065861661373d05e4"
os = "windows"

    [[Wigxjpf.download]]
    sha256 = "3d2c6d83e6a24ea351d5f4cc96f37e34b8235aad4d8417fe8af6d97361a3a8be"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.i686-w64-mingw32.tar.gz"
[[Wigxjpf]]
arch = "powerpc64le"
git-tree-sha1 = "8296517496048d51f4d19561e858917a0310ac4d"
libc = "glibc"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "061c9b98cb4a0412cd193d11ca5d2324ee3279d77af0f8ecd5a5c59cd0e15a9a"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.powerpc64le-linux-gnu.tar.gz"
[[Wigxjpf]]
arch = "riscv64"
git-tree-sha1 = "1646002343207468f7bad16d1ca59834a0331721"
libc = "glibc"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "91252e027352120a5ef7004a54a955e344a1a669470f1e4ae8f9b2ec74a4aec7"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.riscv64-linux-gnu.tar.gz"
[[Wigxjpf]]
arch = "x86_64"
git-tree-sha1 = "111f8c7e5255c404c6e2742c47f346e0b56f0b90"
os = "macos"

    [[Wigxjpf.download]]
    sha256 = "f6f60e6ced7cbfcbf95ac12783f452a6d455c9b3cab967ce3aff3c1770899557"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.x86_64-apple-darwin.tar.gz"
[[Wigxjpf]]
arch = "x86_64"
git-tree-sha1 = "f5b83120bd1fdd6aa83143f11636598f7d564964"
libc = "glibc"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "a6f9ddb01196476ca6bab4f7ae955fa86c85db564477ee726d816c4f8f782d0e"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.x86_64-linux-gnu.tar.gz"
[[Wigxjpf]]
arch = "x86_64"
git-tree-sha1 = "a033a0e0f9b0dc9faa2b07794bb644ae787282ee"
libc = "musl"
os = "linux"

    [[Wigxjpf.download]]
    sha256 = "ab5fe5b98916d7c48582c694f5a17185d4f6b2085e3138cd92e3fd0ca32af434"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.x86_64-linux-musl.tar.gz"
[[Wigxjpf]]
arch = "x86_64"
git-tree-sha1 = "f728eb8fb94a2eee7d417e40372ff08141dcdf95"
os = "freebsd"

    [[Wigxjpf.download]]
    sha256 = "8b465f7f8e62f42886ffdd59d41715600594517b2732e1cf53ebe775947808ff"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.x86_64-unknown-freebsd.tar.gz"
[[Wigxjpf]]
arch = "x86_64"
git-tree-sha1 = "94f105222b11051ad89df210b483debb6abbc115"
os = "windows"

    [[Wigxjpf.download]]
    sha256 = "71951d79e8fe57e06b628b7f367008e65ee795f618ccc9a0e05f4ae7e7178cf9"
    url = "https://github.com/JuliaBinaryWrappers/Wigxjpf_jll.jl/releases/download/Wigxjpf-v1.13.0+0/Wigxjpf.v1.13.0.x86_64-w64-mingw32.tar.gz"
